global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'footballvision'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Load rules
rule_files:
  - 'alerts/*.yml'

# Scrape configurations
scrape_configs:
  # FootballVision Pro metrics
  - job_name: 'footballvision'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  # Jetson metrics (custom exporter)
  - job_name: 'jetson'
    static_configs:
      - targets: ['localhost:9101']
    metrics_path: '/jetson/metrics'