name: Main CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check code structure
        run: |
          # Verify required directories exist
          test -d src/infrastructure
          test -d src/video-pipeline
          test -d src/processing
          test -d src/platform
          test -d tests

      - name: Validate documentation
        run: |
          # Check for required docs
          test -f README.md
          test -f CONTRIBUTING.md
          
  build:
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        component: [infrastructure, video-pipeline, processing, platform]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build ${{ matrix.component }}
        run: |
          echo Building ${{ matrix.component }}
          # Component-specific build will be added by workers
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Run tests
        run: |
          echo Running test suite
          # Test commands will be added by workers
